# fly.toml file generated for openmultiplayer on 2022-08-13T10:47:12+01:00

app = "openmultiplayer"

kill_signal  = "SIGINT"
kill_timeout = 5
processes    = []

[experimental]
    allowed_public_ports = []
    auto_rollback        = true

[env]
    LOG_LEVEL                = "debug"
    PACKAGES_DB              = "/data/packages.db"
    CACHED_SERVERS_FILE      = "/data/cachedServers.json"
    PRODUCTION               = "true"
    PUBLIC_WEB_ADDRESS       = "https://www.open.mp"
    LAUNCHER_BACKEND_ADDRESS = "http://localhost:1420"

[mounts]
    destination = "/data"
    source      = "openmp"

[[services]]
    http_checks   = []
    internal_port = 8000
    processes     = ["app"]
    protocol      = "tcp"
    script_checks = []

    [services.concurrency]
        hard_limit = 25
        soft_limit = 20
        type       = "connections"

    [[services.ports]]
        force_https = true
        handlers    = ["http"]
        port        = 80

    [[services.ports]]
        handlers = ["tls", "http"]
        port     = 443

    [[services.tcp_checks]]
        grace_period  = "1s"
        interval      = "15s"
        restart_limit = 0
        timeout       = "2s"
