name: Test

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "frontend/**"

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/setup-node@v2
      - uses: actions/checkout@v2
      - uses: arduino/setup-task@v1
      - run: go get -v -t -d ./server
      - run: task generate

      - name: Test
        run: go test -v ./server/...
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
